rule_files:
  - bad-rules-error.yml

tests:
  - input_series:
      - series: 'join_1{a="1",b="2"}'
        values: 1
      - series: 'join_2{a="1",b="3"}'
        values: 2
      - series: 'join_2{a="1",b="4"}'
        values: 3

    # Just the existance of the data, that can't be joined, makes the recording
    # rules error.
